import pandas as pd
import numpy as np

class IndicatorManager:
    """Handles technical indicator calculations, specifically RSI."""

    def calculate_rsi(self, df, period=14):
        """
        Calculates the Relative Strength Index (RSI) using Wilder's Smoothing.
        Matches talib.RSI behavior without the C-library dependency.
        Supports both 'Close' and 'close' column names.
        """
        data = df.copy()
        close_col = 'Close' if 'Close' in data.columns else 'close'
        
        if close_col not in data.columns:
            raise KeyError(f"Close column not found. Available: {list(data.columns)}")
            
        # Calculate price changes
        delta = data[close_col].diff()
        
        # Separate gains and losses
        gain = (delta.where(delta > 0, 0))
        loss = (-delta.where(delta < 0, 0))
        
        # Calculate Exponential Moving Average (Wilder's version)
        # alpha = 1 / period
        avg_gain = gain.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
        avg_loss = loss.ewm(alpha=1/period, min_periods=period, adjust=False).mean()
        
        rs = avg_gain / avg_loss
        data['RSI'] = 100 - (100 / (1 + rs))
        
        # Drop NaN values generated by RSI calculation
        data.dropna(subset=['RSI'], inplace=True)
        
        return data
